const query = {
    count_local: "SELECT COUNT(*) CNT FROM LOCAL",
    count_spec: "SELECT COUNT(*) CNT FROM SPEC",
    count_poketmon: "SELECT COUNT(*) CNT FROM POKETMON",
    status_local: "SELECT COUNT(*) CNT, MAX(ID) LASTID FROM LOCAL",
    status_spec: "SELECT COUNT(*) CNT, MAX(ID) LASTID FROM SPEC",
    status_poketmon: "SELECT COUNT(*) CNT, MAX(ID) LASTID FROM POKETMON",
    localdata_local: "SELECT NAME FROM LOCAL",
    localdata_spec: "SELECT NAME FROM SPEC",
    localdata_poketmon: `
    SELECT NAME, RARE, LEVEL_MAX, LEVEL_MIN
    , (SELECT PATH FROM IMAGE WHERE ID=IMAGE_ID LIMIT 1) PATH
    , (SELECT NAME FROM LOCAL WHERE ID=LOCAL_ID LIMIT 1) LOCAL
    , (SELECT NAME FROM SPEC WHERE ID=SPEC1 LIMIT 1) SPEC1
    , (SELECT NAME FROM SPEC WHERE ID=SPEC2 LIMIT 1) SPEC2
    , (SELECT NAME FROM SPEC WHERE ID=SPEC3 LIMIT 1) SPEC3
    FROM (
        SELECT P.NAME, MAX(RARE) RARE, MAX(LEVEL_MAX) LEVEL_MAX, MAX(LEVEL_MIN) LEVEL_MIN
        , MAX(IMAGE_ID) IMAGE_ID, MAX(LOCAL_ID) LOCAL_ID
        , MAX(CASE WHEN PRIORITY=1 THEN PS.SPEC_ID ELSE 0 END) SPEC1
        , MAX(CASE WHEN PRIORITY=2 THEN PS.SPEC_ID ELSE 0 END) SPEC2
        , MAX(CASE WHEN PRIORITY=3 THEN PS.SPEC_ID ELSE 0 END) SPEC3
        FROM POKETMON P
        LEFT JOIN POKETMON_IMAGE PI ON PI.POKETMON_ID=P.ID
        LEFT JOIN POKETMON_SPEC PS ON PS.POKETMON_ID=P.ID
        LEFT JOIN POKETMON_LOCAL PL ON PL.POKETMON_ID=P.ID
        GROUP BY P.NAME
    ) A
    `,
    alldata_local: "SELECT * FROM LOCAL",
    alldata_spec: "SELECT * FROM SPEC",
    alldata_poketmon: "SELECT * FROM POKETMON",
    alldata_image: "SELECT * FROM IMAGE",
    alldata_poketmon_local: "SELECT * FROM POKETMON_LOCAL",
    alldata_poketmon_spec: "SELECT * FROM POKETMON_SPEC",
    alldata_poketmon_image: "SELECT * FROM POKETMON_IMAGE",
    id_local: "SELECT ID ID FROM LOCAL WHERE NAME=@name",
    id_spec: "SELECT ID ID FROM SPEC WHERE NAME=@name",
    id_poketmon: "SELECT ID ID FROM POKETMON WHERE NAME=@name",
};

module.exports = query;
